model_id: 'Qwen/Qwen2.5-Math-7B-Instruct'
train_data_path: './data/prm800k_train_reprocessed.json'
eval_data_path: './data/prm800k_phase2_eval_small.json'
max_length: 650
train_label_last_n: 1
eval_label_last_n: 1
wandb_project: 'prm_train'
training_args:
  output_dir: './runs/qwen_prm800k'
  learning_rate: 1.25e-6
  gradient_accumulation_steps: 16
  eval_accumulation_steps: 3
  lr_scheduler_type: 'cosine' 
  warmup_ratio: 0.1
  bf16: true
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 4
  num_train_epochs: 1
  weight_decay: 0.01
  eval_strategy: 'steps'
  eval_steps: 5
  eval_on_start: true
  logging_steps: 1
  save_strategy: 'steps'
  save_steps: 500
  save_total_limit: 1
  load_best_model_at_end: false
  push_to_hub: true
  hub_token: null # replace with token
  hub_strategy: 'checkpoint'
  seed: 908932403
  data_seed: 289245
  use_liger_kernel: true
