model_id: 'Daewon0808/prm800k_llama_fulltune'
train_data_path: './data/mmlu_auged.json'
eval_data_path: null
max_length: 750
train_label_last_n: 1
eval_label_last_n: 1
wandb_project: 'prm_train'
lora_config:
  r: 16
  lora_alpha: 32  
  lora_dropout: 0.1
  target_modules: 'all-linear'
  task_type: 'CAUSAL_LM'
training_args:
  output_dir: './runs/versa_prm_auged'
  learning_rate: 1.0e-4
  gradient_accumulation_steps: 2
  eval_accumulation_steps: 3
  lr_scheduler_type: 'cosine' 
  warmup_ratio: 0.1
  bf16: true
  per_device_train_batch_size: 4
  num_train_epochs: 1
  weight_decay: 0.01
  eval_strategy: 'no'
  logging_steps: 1
  save_strategy: 'steps'
  save_steps: 500
  save_total_limit: 1
  load_best_model_at_end: false
  push_to_hub: true
  hub_strategy: 'checkpoint'
  seed: 908932403
  data_seed: 289245
  use_liger_kernel: false
